### ISSUE TITLE
List required build components

### ISSUE THREAD

**Issue by Faeranne** [SirDavidLudwig/OpenComputers-Reimagined#2]
It's been a while since I've done any mod development, but I'd like to help move OC into the 1.16 era, especially as I am interesting in restarting development on oc-js.  Unfortunently, I can't seem to get a proper build going.  I can see I need `kotori_scala`, but even after adding the file from scalable-cats-force. I get errors in the build.  It seems I'm still missing something.  I'd upload a log, but each time it complains about a different class missing, so I'm guessing I'm just straight up missing a step.

Steps I've taken so far:
1. Install Intellij IDEA (version 2020.1)
2. Git Clone the project
3. `./gradlew genIntellijRuns`
4. Add scalable-cats-force to run/mods
5. Attempt to run the client.

At this point, the client does open a window, but just after the loader finishes, it errors out.

I can't list the other ClassNotFoundExceptions, but the latest one is below:
```
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/Mixins
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_191] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_191] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) [?:1.8.0_191] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191] {}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] {}
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/Mixins
	at com.kotori316.scala_lib.ScalaLanguageProvider$.<clinit>(ScalaLanguageProvider.scala:50) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at com.kotori316.scala_lib.ScalaLanguageProvider.$anonfun$getFileVisitor$2(ScalaLanguageProvider.scala:21) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at com.kotori316.scala_lib.ScalaLanguageProvider.$anonfun$getFileVisitor$2$adapted(ScalaLanguageProvider.scala:21) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:472) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.Growable.addAll(Growable.scala:61) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.Growable.addAll$(Growable.scala:59) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.HashSet.addAll(HashSet.scala:100) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.HashSet$.from(HashSet.scala:30) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.HashSet$.from(HashSet.scala:371) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableFactoryDefaults.fromSpecific(Iterable.scala:930) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableFactoryDefaults.fromSpecific$(Iterable.scala:930) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.AbstractIterable.fromSpecific(Iterable.scala:920) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.AbstractIterable.fromSpecific(Iterable.scala:920) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableOps.filter(Iterable.scala:398) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableOps.filter$(Iterable.scala:398) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.AbstractIterable.filter(Iterable.scala:920) ~[scala-library-2.13.2.jar:?] {}
	at com.kotori316.scala_lib.ScalaLanguageProvider.$anonfun$getFileVisitor$1(ScalaLanguageProvider.scala:21) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:50) ~[forge-1.16.1-32.0.70_mapped_snapshot_20200514-1.16-launcher.jar:?] {}
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:131) ~[forge-1.16.1-32.0.70_mapped_snapshot_20200514-1.16-launcher.jar:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191] {}
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.mixin.Mixins
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191] {}
	at com.kotori316.scala_lib.ScalaLanguageProvider$.<clinit>(ScalaLanguageProvider.scala:50) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at com.kotori316.scala_lib.ScalaLanguageProvider.$anonfun$getFileVisitor$2(ScalaLanguageProvider.scala:21) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at com.kotori316.scala_lib.ScalaLanguageProvider.$anonfun$getFileVisitor$2$adapted(ScalaLanguageProvider.scala:21) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:472) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.Growable.addAll(Growable.scala:61) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.Growable.addAll$(Growable.scala:59) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.HashSet.addAll(HashSet.scala:100) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.HashSet$.from(HashSet.scala:30) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.mutable.HashSet$.from(HashSet.scala:371) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableFactoryDefaults.fromSpecific(Iterable.scala:930) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableFactoryDefaults.fromSpecific$(Iterable.scala:930) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.AbstractIterable.fromSpecific(Iterable.scala:920) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.AbstractIterable.fromSpecific(Iterable.scala:920) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableOps.filter(Iterable.scala:398) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.IterableOps.filter$(Iterable.scala:398) ~[scala-library-2.13.2.jar:?] {}
	at scala.collection.AbstractIterable.filter(Iterable.scala:920) ~[scala-library-2.13.2.jar:?] {}
	at com.kotori316.scala_lib.ScalaLanguageProvider.$anonfun$getFileVisitor$1(ScalaLanguageProvider.scala:21) ~[ScalableCatsForce-2.13.3-build-6-with-library.jar:2.13.3-build-6] {}
	at net.minecraftforge.fml.loading.moddiscovery.Scanner.scan(Scanner.java:50) ~[forge-1.16.1-32.0.70_mapped_snapshot_20200514-1.16-launcher.jar:?] {}
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.compileContent(ModFile.java:131) ~[forge-1.16.1-32.0.70_mapped_snapshot_20200514-1.16-launcher.jar:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191] {}
	... 3 more
```

**Comment by Faeranne** [comment]
Changed the name, as I found that the issue is due to having downloaded the latest `scalable-cats-force` when specifically `2.13.2-build-2` is needed.  The fact that the minor versions of scalable-cats-force aren't compatible isn't really your fault, but mentioning it in the readme or elsewhere would help kickstart people helping out with the project.

**Comment by SirDavidLudwig** [comment]
I've been busy with my master's degree as it was my last semester and finish that recently. Honestly didn't expect anyone to try messing this repo which is why I haven't done any kind of readme lol. I'll be picking up development on this again very soon. Since a few people now seem interested I'll work on that.
